[package]
name = "destroy"
version = "0.0.2"
authors = ["ashtneoi <ashtneoi@gmail.com>"]
license = "MIT"

[dependencies]
grow-collections = { path = "grow-collections" }
splop = "0.2.0"
tree-cursor = { path = "tree-cursor" }
